#!/bin/bash
#SBATCH -A snic2022-22-1049
#SBATCH -p node
#SBATCH -C mem512GB
#SBATCH -M snowy
#SBATCH -J steps_othercelltypes_SCSR
#SBATCH -t 240:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

module load R_packages/4.1.1

Rscript R_script_othercelltypes.R

